export enum GameEvents {
  CONNECTION = 'connection',
  DISCONNECTION = 'disconnect',
  LEAVE_ROOM = 'leave room',
  MASTER_ENTRY = 'master entry',
  MASTER_STATISTICS = 'master statistics',
  SESSION = 'session',
  PARTICIPANT_NOTICE = 'participant notice',
  PARTICIPANT_INFO = 'participant info',
  PARTICIPANT_STATISTICS = 'participant statistics',
  START_QUIZ = 'start quiz',
  SHOW_QUIZ = 'show quiz',
  SUBMIT_ANSWER = 'submit answer',
  EMOJI = 'emoji',
  TIME_END = 'time end',
  SHOW_RANKING = 'show ranking',
  END_QUIZ = 'end quiz',
  LEADERBOARD = 'leaderboard',
  MESSAGE = 'message',
  MY_INFO = 'my info',
  // 클라이언트 이벤트
  PINCODE = 'pincode',
}
